apiVersion: v1
kind: Service
metadata:
  name: simpletimeservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: simpletimeservice
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
